### ISSUE TITLE
Background rendering exceptions

### ISSUE THREAD

**Issue by devdave25** [cr1pto/simple_bible#5]
I am receiving the following exception repeatedly on the background whilst I am running the app.

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderPointerListener#af999 relayoutBoundary=up12 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2009 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Autocomplete<String> Autocomplete:file:///C:/Users/david/Documents/DevDave/repo/simple_bible/lib/screens/book_search_screen.dart:27:11
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2009:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:121:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#12     RenderTapRegion.layout (package:flutter/src/widgets/tap_region.dart:493:11)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#15     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#17     RenderLeaderLayer.performLayout (package:flutter/src/rendering/proxy_box.dart:4792:11)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#19     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#22     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#25     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#26     RenderTapRegion.layout (package:flutter/src/widgets/tap_region.dart:493:11)
#27     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#28     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:836:43)
#29     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:938:32)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#31     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#32     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#33     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1074:7)
#34     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#35     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#37     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1467:11)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2148:7)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2426:11)
#45     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#46     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1074:7)
#47     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#48     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
#49     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1986:7)
#50     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1012:18)
#51     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:509:19)
#52     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#53     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:374:5)
#54     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#55     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#56     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#57     _invoke (dart:ui/hooks.dart:145:13)
#58     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:320:5)
#59     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#6ab5d relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=718.3)
...  size: MISSING
RenderObject: RenderSemanticsAnnotations#6ab5d relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=718.3)
  size: MISSING
...  child: RenderPointerListener#af999 relayoutBoundary=up12 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=718.3)
...    size: MISSING
...    behavior: translucent
...    listeners: down, panZoomStart
...    child: _RenderDecoration#8d815 relayoutBoundary=up13 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=718.3)
...      size: MISSING
...      input: RenderRepaintBoundary#dfbb5 NEEDS-LAYOUT NEEDS-PAINT
...        needs compositing
...        parentData: offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        layer: OffsetLayer#0d6b0 DETACHED
...          handles: 1
...          offset: Offset(0.0, 0.0)
...        size: MISSING
...        metrics: 0.0% useful (41 bad vs 0 good)
...        diagnosis: this repaint boundary is astoundingly ineffectual and should be removed
...        child: RenderTapRegion#44b92
...          debugLabel: EditableText
...          groupId: EditableText
...      helperError: RenderConstrainedBox#fcb8e NEEDS-LAYOUT NEEDS-PAINT
...        parentData: offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        size: MISSING
...        additionalConstraints: BoxConstraints(w=0.0, h=0.0)
...      container: RenderCustomPaint#303aa NEEDS-LAYOUT NEEDS-PAINT
...        parentData: offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        size: MISSING
...        painter: null
...        foregroundPainter: _InputBorderPainter#bcc07
```

**Comment by cr1pto** [comment]
This should be fixed now.
